### PR TITLE
Replaced potentially dangerous bus interaction in the Read() method

### PR DESCRIPTION
**Pull request by ConnorKirkpatrick**
The change alters the read() method to prevent the system from handing off control of the i2c bus before data has been received. This is done by altering the endTranmission() call to use the parameter false to prevent the handoff, and then adding the parameter true to the end of requestFrom() to hand off the bus once the required amount of bytes has been received.

This change aims to prevent lockup conditions on a populated bus, where the handoff of the bus by the read method may lead to another device being polled and the method receiving incorrect/invalid data for further processing.
This was observed on an populated bus with a MPU-6050, BMP-280 and the HMC5883l, causing the system to hang after about 2 minutes of run time.
The new system was observed to run for an excess of 25 minutes before observation was ended

The overall code/library does not function noticeably different than before, and this fork exists only to prevent issues that would arise in niche cases without changing the performance in any other cases.

### CODE REVIEW

**Review by ladyada — APPROVED** [review]
tbh this chip is discontinued so we are cool with the PR but wont be testing

**Comment by ladyada** [comment]
hiya! thanks so much for submitting a PR! we can review & merge PRs once they have passed continuous integration (CI). that means that code compiles cleanly for all tested platforms, is clang formatted so we maintain the same text formatting for all new code, and is doxygen documented.
if your code isnt passing, check the CI output (click on the red X next to the PR to scroll through the log and find where the error is

here is a tutorial on doxygen: https://learn.adafruit.com/the-well-automated-arduino-library/doxygen

and clang-format: https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format

and overall how to contribute PRs to libraries: https://learn.adafruit.com/contribute-to-arduino-with-git-and-github

once you get that green checkmark that indicates CI has passed, please comment reply to this post so we know its time for another review (we may not get notified on CI pass and miss that its time to look!)

**Comment by ConnorKirkpatrick** [comment]
Not entirely sure why the Clang action is failing here, the file is directly piped from the local CLI and the error occurs after the end of the file which is odd.

**Comment by ladyada** [comment]
you can run clang-format on the file to fix any format issues. it could be a missing CRLF

**Comment by ladyada** [comment]
@caternuson kindly made a PR that is clang-formatted, we'll bump the library later this week! thanks :)
https://github.com/adafruit/Adafruit_HMC5883_Unified/pull/12

**Pull request closed without merging**
